/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package menu;

import java.sql.Connection;
import static sys.MainFrame.medicdspane;

/**
 *
 * @author saleem
 */
public class Warehouse extends javax.swing.JInternalFrame {

    public static Connection connectDB;
    public static String username;

    /**
     * Creates new form NewRecords
     */
    public Warehouse(java.sql.Connection conndb, String user) {
        connectDB = conndb;
        username = user;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jButton1 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jButton14 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        jButton15 = new javax.swing.JButton();
        jButton16 = new javax.swing.JButton();
        jButton12 = new javax.swing.JButton();
        jButton13 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Warehouse");
        getContentPane().setLayout(new java.awt.GridBagLayout());

        jButton1.setFont(new java.awt.Font("Padauk Book", 1, 12)); // NOI18N
        jButton1.setForeground(new java.awt.Color(0, 51, 204));
        jButton1.setMnemonic('r');
        jButton1.setText("Receiving Stock");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(50, 50, 50, 50);
        getContentPane().add(jButton1, gridBagConstraints);

        jButton7.setFont(new java.awt.Font("Padauk Book", 1, 12)); // NOI18N
        jButton7.setForeground(new java.awt.Color(0, 51, 204));
        jButton7.setMnemonic('1');
        jButton7.setText("Level 1 Inspection");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(50, 50, 50, 50);
        getContentPane().add(jButton7, gridBagConstraints);

        jButton8.setFont(new java.awt.Font("Padauk Book", 1, 12)); // NOI18N
        jButton8.setForeground(new java.awt.Color(0, 51, 204));
        jButton8.setMnemonic('2');
        jButton8.setText("Level 2 Inspection");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(50, 50, 50, 50);
        getContentPane().add(jButton8, gridBagConstraints);

        jButton9.setFont(new java.awt.Font("Padauk Book", 1, 12)); // NOI18N
        jButton9.setForeground(new java.awt.Color(0, 51, 204));
        jButton9.setMnemonic('l');
        jButton9.setText("Stock Transfer");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(50, 50, 50, 50);
        getContentPane().add(jButton9, gridBagConstraints);

        jButton10.setFont(new java.awt.Font("Padauk Book", 1, 12)); // NOI18N
        jButton10.setForeground(new java.awt.Color(0, 51, 204));
        jButton10.setMnemonic('3');
        jButton10.setText("Level 3 Inspection");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(50, 50, 50, 50);
        getContentPane().add(jButton10, gridBagConstraints);

        jButton14.setFont(new java.awt.Font("Padauk Book", 1, 12)); // NOI18N
        jButton14.setForeground(new java.awt.Color(0, 51, 204));
        jButton14.setMnemonic('g');
        jButton14.setText("GRN Reversal");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(50, 50, 50, 50);
        getContentPane().add(jButton14, gridBagConstraints);

        jButton11.setFont(new java.awt.Font("Padauk Book", 1, 12)); // NOI18N
        jButton11.setForeground(new java.awt.Color(0, 51, 204));
        jButton11.setMnemonic('l');
        jButton11.setText("Register LPO");
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(50, 50, 50, 50);
        getContentPane().add(jButton11, gridBagConstraints);

        jButton15.setFont(new java.awt.Font("Padauk Book", 1, 12)); // NOI18N
        jButton15.setForeground(new java.awt.Color(0, 51, 204));
        jButton15.setMnemonic('g');
        jButton15.setText("Grn/Inspection certificate");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(50, 50, 50, 50);
        getContentPane().add(jButton15, gridBagConstraints);

        jButton16.setFont(new java.awt.Font("Padauk Book", 1, 12)); // NOI18N
        jButton16.setForeground(new java.awt.Color(0, 51, 204));
        jButton16.setMnemonic('g');
        jButton16.setText("Stock Returns");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(50, 50, 50, 50);
        getContentPane().add(jButton16, gridBagConstraints);

        jButton12.setFont(new java.awt.Font("Padauk Book", 1, 12)); // NOI18N
        jButton12.setForeground(new java.awt.Color(0, 51, 204));
        jButton12.setMnemonic('l');
        jButton12.setText("Requisitions");
        jButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton12ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(50, 50, 50, 50);
        getContentPane().add(jButton12, gridBagConstraints);

        jButton13.setFont(new java.awt.Font("Padauk Book", 1, 12)); // NOI18N
        jButton13.setForeground(new java.awt.Color(0, 51, 204));
        jButton13.setMnemonic('l');
        jButton13.setText("Requisition Authorization");
        jButton13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton13ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(50, 50, 50, 50);
        getContentPane().add(jButton13, gridBagConstraints);

        jButton4.setFont(new java.awt.Font("Padauk Book", 1, 12)); // NOI18N
        jButton4.setForeground(new java.awt.Color(0, 51, 204));
        jButton4.setMnemonic('b');
        jButton4.setText("Stock Reconciliation");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(50, 50, 50, 50);
        getContentPane().add(jButton4, gridBagConstraints);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
        // TODO add your handling code here:
        this.dispose();
        inventory.RegisterLpo comp = new inventory.RegisterLpo(connectDB, username);
        medicdspane.add(comp, javax.swing.JLayeredPane.DEFAULT_LAYER);
        comp.setVisible(true);
        comp.setSize(medicdspane.getSize());
    }//GEN-LAST:event_jButton11ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
         this.dispose();
        inventory.ReceivingStock comp = new inventory.ReceivingStock(connectDB, username);
        medicdspane.add(comp, javax.swing.JLayeredPane.DEFAULT_LAYER);
        comp.setVisible(true);
        comp.setSize(medicdspane.getSize());
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
        this.dispose();
        inventory.Level1Inspection comp = new inventory.Level1Inspection(connectDB, username);
        medicdspane.add(comp, javax.swing.JLayeredPane.DEFAULT_LAYER);
        comp.setVisible(true);
        comp.setSize(medicdspane.getSize());
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton12ActionPerformed
        // TODO add your handling code here:
         this.dispose();
        inventory.RaiseExternalPrInfr comp = new inventory.RaiseExternalPrInfr(connectDB, username);
        medicdspane.add(comp, javax.swing.JLayeredPane.DEFAULT_LAYER);
        comp.setVisible(true);
        comp.setSize(medicdspane.getSize());
    }//GEN-LAST:event_jButton12ActionPerformed

    private void jButton13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton13ActionPerformed
        // TODO add your handling code here:
         this.dispose();
        inventory.ApproveRequisitions comp = new inventory.ApproveRequisitions(connectDB, username);
        medicdspane.add(comp, javax.swing.JLayeredPane.DEFAULT_LAYER);
        comp.setVisible(true);
        comp.setSize(medicdspane.getSize());
    }//GEN-LAST:event_jButton13ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton14;
    private javax.swing.JButton jButton15;
    private javax.swing.JButton jButton16;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    // End of variables declaration//GEN-END:variables
}
