/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package utility;

/**
 *
 * @author Wilson Gitau
 */
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.FileInputStream;
import java.io.InputStream;
import java.sql.Connection;
import java.sql.ResultSet;
import javax.imageio.ImageIO;
import javax.swing.filechooser.FileNameExtensionFilter;

public class Logo extends javax.swing.JInternalFrame {

    /**
     * Creates new form Logo
     */
    public static Connection connectDB;
    public static String username;
    String waterMarkFile, imagesDir;

    public Logo(java.sql.Connection conndb, String user) {
        connectDB = conndb;
        username = user;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel4 = new javax.swing.JPanel();
        waterMarkBtn = new javax.swing.JButton();
        waterMarkPreviewLbl = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        Slogan = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        saveData = new javax.swing.JButton();
        clearbtn = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        Tel = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        fax = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        name = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        address = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Company Logo");
        getContentPane().setLayout(new java.awt.GridBagLayout());

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder("Create a profile"));
        jPanel4.setLayout(new java.awt.GridBagLayout());

        waterMarkBtn.setText("Browse Logo");
        waterMarkBtn.setToolTipText("Click to select watermark image");
        waterMarkBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                waterMarkBtnActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        jPanel4.add(waterMarkBtn, gridBagConstraints);

        waterMarkPreviewLbl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/Pics.png"))); // NOI18N
        waterMarkPreviewLbl.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.gridheight = 3;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        jPanel4.add(waterMarkPreviewLbl, gridBagConstraints);

        jLabel1.setText("Slogan");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        jPanel4.add(jLabel1, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        jPanel4.add(Slogan, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.gridwidth = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        jPanel4.add(jSeparator1, gridBagConstraints);

        saveData.setMnemonic('O');
        saveData.setText("Save");
        saveData.setToolTipText("Click here to enter data");
        saveData.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveDataActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        jPanel4.add(saveData, gridBagConstraints);

        clearbtn.setMnemonic('l');
        clearbtn.setText("Clear");
        clearbtn.setToolTipText("Click here to clear fields");
        clearbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearbtnActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        jPanel4.add(clearbtn, gridBagConstraints);

        jLabel2.setText("Tel");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        jPanel4.add(jLabel2, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        jPanel4.add(Tel, gridBagConstraints);

        jLabel3.setText("Fax");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        jPanel4.add(jLabel3, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        jPanel4.add(fax, gridBagConstraints);

        jLabel4.setText("Company Name");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        jPanel4.add(jLabel4, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        jPanel4.add(name, gridBagConstraints);

        jLabel5.setText("Postal Address");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        jPanel4.add(jLabel5, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        jPanel4.add(address, gridBagConstraints);

        jButton1.setText("View Current Profile");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 6;
        jPanel4.add(jButton1, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridheight = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 10.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 5, 5, 5);
        getContentPane().add(jPanel4, gridBagConstraints);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void waterMarkBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_waterMarkBtnActionPerformed

        javax.swing.JFileChooser fileChooser = new javax.swing.JFileChooser(System.getProperty("images.dir"));

        FileNameExtensionFilter filter = new FileNameExtensionFilter("Image files (*.jpg, *.png, *.gif)", "jpg", "png", "gif");

        fileChooser.setFileFilter(filter);

        fileChooser.showOpenDialog(this);

        waterMarkPreviewLbl.setIcon(new javax.swing.ImageIcon(fileChooser.getSelectedFile().getPath()));

        waterMarkFile = fileChooser.getSelectedFile().getPath();

        imagesDir = fileChooser.getSelectedFile().getParent();

        System.setProperty("images.dir", fileChooser.getSelectedFile().getParent());
        System.out.println(waterMarkFile);
        System.out.println(imagesDir);
        // TODO add your handling code here:
    }//GEN-LAST:event_waterMarkBtnActionPerformed

    private void saveDataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveDataActionPerformed

        try {
            File file = new File(waterMarkFile);
            FileInputStream fis = new FileInputStream(file);

            connectDB.setAutoCommit(false);
            java.sql.PreparedStatement pstmt311 = connectDB.prepareStatement("delete from institution_profile");
            pstmt311.executeUpdate();
            java.sql.PreparedStatement pstmt = connectDB.prepareStatement("insert into institution_profile (name,box_no,main_tel,main_fax,slogan,logo) values(upper(?),upper(?),upper(?),upper(?),upper(?),?)");
            pstmt.setObject(1, name.getText());
            pstmt.setObject(2, address.getText());
            pstmt.setObject(3, Tel.getText());
            pstmt.setObject(4, fax.getText());
            pstmt.setObject(5, Slogan.getText());
            pstmt.setBinaryStream(6, fis, (int) file.length());
            pstmt.executeUpdate();
            connectDB.commit();
            connectDB.setAutoCommit(true);

            javax.swing.JOptionPane.showMessageDialog(this, "Data saved successfully", "Confirmation Message", javax.swing.JOptionPane.INFORMATION_MESSAGE);
            clearbtn.doClick();
        } catch (Exception sq) {
            javax.swing.JOptionPane.showMessageDialog(this, sq.getMessage(), "Error Message!", javax.swing.JOptionPane.ERROR_MESSAGE);
            try {
                connectDB.rollback();
            } catch (java.sql.SQLException sql) {
                javax.swing.JOptionPane.showMessageDialog(this, sql.getMessage(), "Error Message!", javax.swing.JOptionPane.ERROR_MESSAGE);
            }
        }
        // Add your handling code here:
    }//GEN-LAST:event_saveDataActionPerformed

    private void clearbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearbtnActionPerformed
        name.setText("");
        Tel.setText("");
        Slogan.setText("");
        fax.setText("");
        address.setText("");
        waterMarkPreviewLbl.setText("");
        // Add your handling code here:
    }//GEN-LAST:event_clearbtnActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        try {
           java.sql.PreparedStatement pstmt = connectDB.prepareStatement("SELECT name,logo,box_no,main_tel,main_fax,slogan from institution_profile");
            ResultSet rs = pstmt.executeQuery();
            if (rs.next()) {
                InputStream is = rs.getBinaryStream(2);
                BufferedImage img= ImageIO.read(is);
                waterMarkPreviewLbl.setIcon(new javax.swing.ImageIcon(img));
                name.setText(rs.getString("name"));
                Tel.setText(rs.getString("main_tel"));
                Slogan.setText(rs.getString("slogan"));
                fax.setText(rs.getString("main_fax"));
                address.setText(rs.getString("box_no"));
            }
        } catch (Exception y) {

        }
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Slogan;
    private javax.swing.JTextField Tel;
    private javax.swing.JTextField address;
    private javax.swing.JButton clearbtn;
    private javax.swing.JTextField fax;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField name;
    private javax.swing.JButton saveData;
    private javax.swing.JButton waterMarkBtn;
    private javax.swing.JLabel waterMarkPreviewLbl;
    // End of variables declaration//GEN-END:variables
}
