/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sys;

import inventory.ReceivingStock;
import java.util.Vector;
import javax.swing.JOptionPane;
import menu.NewRecord;
import menu.Pharmacy;
import menu.Reports;
import menu.Settings;
import menu.Warehouse;

/**
 *
 * @author saleem
 */
public class MainFrame extends javax.swing.JFrame {

    /**
     * Creates new form MainFrame
     */
    public static java.sql.Connection connectDB;
    public static Object[] privileges;
    public static String username;

    public MainFrame(java.sql.Connection connDB, String user) {
        this.setExtendedState(MAXIMIZED_BOTH);
        connectDB = connDB;

        username = user;
        initComponents();

        userbt.setLabel(username);
        // MainFrame.medicdspane hospmain = new javax.swing.JDesktopPane();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        mainPanel = new javax.swing.JPanel();
        jToolBar2 = new javax.swing.JToolBar();
        jPanel2 = new javax.swing.JPanel();
        jToolBar3 = new javax.swing.JToolBar();
        New_Recordbtin = new javax.swing.JButton();
        Warehousebtin = new javax.swing.JButton();
        Pharmacybtin = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        userbt = new javax.swing.JButton();
        Reportsbtin = new javax.swing.JButton();
        Settingsbtin = new javax.swing.JButton();
        medicdspane = new javax.swing.JDesktopPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Supply Chain Management");
        getContentPane().setLayout(new java.awt.GridBagLayout());

        mainPanel.setLayout(new java.awt.GridBagLayout());

        jToolBar2.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jToolBar2.setFloatable(false);

        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel2.setLayout(new java.awt.GridBagLayout());

        jToolBar3.setBackground(new java.awt.Color(255, 255, 255));
        jToolBar3.setBorder(null);
        jToolBar3.setRollover(true);

        New_Recordbtin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/new.png"))); // NOI18N
        New_Recordbtin.setText("New Record");
        New_Recordbtin.setToolTipText("Add new record (item, supplier,etc)");
        New_Recordbtin.setBorder(null);
        New_Recordbtin.setFocusable(false);
        New_Recordbtin.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        New_Recordbtin.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        New_Recordbtin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                New_RecordbtinActionPerformed(evt);
            }
        });
        jToolBar3.add(New_Recordbtin);

        Warehousebtin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/inventory.jpeg"))); // NOI18N
        Warehousebtin.setText("Warehouse");
        Warehousebtin.setToolTipText("inventory transactions (receiving,transfer, stock returns etc)");
        Warehousebtin.setBorder(null);
        Warehousebtin.setFocusable(false);
        Warehousebtin.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Warehousebtin.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        Warehousebtin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                WarehousebtinActionPerformed(evt);
            }
        });
        jToolBar3.add(Warehousebtin);
        Warehousebtin.getAccessibleContext().setAccessibleName("transactionsbtin");

        Pharmacybtin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/pharmacy sale.png"))); // NOI18N
        Pharmacybtin.setText("Pharmacy");
        Pharmacybtin.setToolTipText("Pharmacy sales (POS, credit sales, dispensing and invoicing)");
        Pharmacybtin.setBorder(null);
        Pharmacybtin.setFocusable(false);
        Pharmacybtin.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Pharmacybtin.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        Pharmacybtin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PharmacybtinActionPerformed(evt);
            }
        });
        jToolBar3.add(Pharmacybtin);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new java.awt.GridBagLayout());

        jLabel1.setText("Bespoke Inventory System v1.0");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        jPanel1.add(jLabel1, gridBagConstraints);

        userbt.setBackground(new java.awt.Color(255, 255, 255));
        userbt.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/userbg.png"))); // NOI18N
        userbt.setBorder(null);
        userbt.setFocusable(false);
        userbt.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        userbt.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jPanel1.add(userbt, new java.awt.GridBagConstraints());

        jToolBar3.add(jPanel1);

        Reportsbtin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/inventory report.jpeg"))); // NOI18N
        Reportsbtin.setText("Reports");
        Reportsbtin.setToolTipText("All inventory reports");
        Reportsbtin.setBorder(null);
        Reportsbtin.setFocusable(false);
        Reportsbtin.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Reportsbtin.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        Reportsbtin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ReportsbtinActionPerformed(evt);
            }
        });
        jToolBar3.add(Reportsbtin);

        Settingsbtin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/config.jpeg"))); // NOI18N
        Settingsbtin.setText("Settings");
        Settingsbtin.setToolTipText("System Settings");
        Settingsbtin.setBorder(null);
        Settingsbtin.setFocusable(false);
        Settingsbtin.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Settingsbtin.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        Settingsbtin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SettingsbtinActionPerformed(evt);
            }
        });
        jToolBar3.add(Settingsbtin);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        jPanel2.add(jToolBar3, gridBagConstraints);

        jToolBar2.add(jPanel2);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.weightx = 1.0;
        mainPanel.add(jToolBar2, gridBagConstraints);

        medicdspane.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                medicdspaneFocusGained(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 10.0;
        mainPanel.add(medicdspane, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        getContentPane().add(mainPanel, gridBagConstraints);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void medicdspaneFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_medicdspaneFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_medicdspaneFocusGained

    private void New_RecordbtinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_New_RecordbtinActionPerformed
        // TODO add your handling code here:
        NewRecord comp = new NewRecord(connectDB, username);
        medicdspane.add(comp, javax.swing.JLayeredPane.DEFAULT_LAYER);
        comp.setVisible(true);
        comp.setSize(medicdspane.getSize());
    }//GEN-LAST:event_New_RecordbtinActionPerformed

    private void WarehousebtinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_WarehousebtinActionPerformed
        // TODO add your handling code here:

        Warehouse comp = new Warehouse(connectDB, username);
        medicdspane.add(comp, javax.swing.JLayeredPane.DEFAULT_LAYER);
        comp.setVisible(true);
        comp.setSize(medicdspane.getSize());

    }//GEN-LAST:event_WarehousebtinActionPerformed

    private void PharmacybtinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PharmacybtinActionPerformed
        // TODO add your handling code here:
        Pharmacy comp = new Pharmacy(connectDB, username);
        medicdspane.add(comp, javax.swing.JLayeredPane.DEFAULT_LAYER);
        comp.setVisible(true);
        comp.setSize(medicdspane.getSize());
    }//GEN-LAST:event_PharmacybtinActionPerformed

    private void ReportsbtinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ReportsbtinActionPerformed
        // TODO add your handling code here:
        Reports comp = new Reports(connectDB, username);
        medicdspane.add(comp, javax.swing.JLayeredPane.DEFAULT_LAYER);
        comp.setVisible(true);
        comp.setSize(medicdspane.getSize());
    }//GEN-LAST:event_ReportsbtinActionPerformed

    private void SettingsbtinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SettingsbtinActionPerformed
        // TODO add your handling code here:
        Settings comp = new Settings(connectDB, username);
        medicdspane.add(comp, javax.swing.JLayeredPane.DEFAULT_LAYER);
        comp.setVisible(true);
        comp.setSize(medicdspane.getSize());
    }//GEN-LAST:event_SettingsbtinActionPerformed

    public static void actions(String var_name) {
        System.err.println(var_name + " Done");

    }

    public static Vector AllocatedDomains(String username) {
        Vector domains = new Vector();

        return domains;
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrame(connectDB, username).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JButton New_Recordbtin;
    public static javax.swing.JButton Pharmacybtin;
    public static javax.swing.JButton Reportsbtin;
    public static javax.swing.JButton Settingsbtin;
    public static javax.swing.JButton Warehousebtin;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JToolBar jToolBar2;
    private javax.swing.JToolBar jToolBar3;
    private javax.swing.JPanel mainPanel;
    public static javax.swing.JDesktopPane medicdspane;
    private javax.swing.JButton userbt;
    // End of variables declaration//GEN-END:variables
}
