/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package inventory;

import java.awt.Color;
import java.awt.Desktop;
import java.beans.PropertyVetoException;
import java.io.File;
import java.io.IOException;
import java.sql.Date;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author saleem
 */
public class RaiseExternalPrInfr extends javax.swing.JInternalFrame {

    /**
     * Creates new form RaiseExternalPrInfr
     */
    java.sql.Connection connectDB = null;
    org.netbeans.lib.sql.pool.PooledConnectionSource pConnDB = null;
    Boolean JOptionCheck = false;
    String userName = null;
    private int maxIndex;
    private int index1;

    public RaiseExternalPrInfr(java.sql.Connection connDb, String user) {

        connectDB = connDb;

        userName = user;

        initComponents();

        userTxt.setText(userName);

        String title = "Raising a Requisition for Items";

        setTitle("TRANSACTION TYPE:" + title);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        itemsReqDialog = new javax.swing.JDialog();
        jSearchPanel1 = new javax.swing.JPanel();
        jTextField1111 = new javax.swing.JTextField();
        jSearchScrollPane1 = new javax.swing.JScrollPane();
        itemsReqtbl = new dbadmin.JTable();
        jButton91 = new javax.swing.JButton();
        jSearchDialog11 = new javax.swing.JDialog();
        jSearchPanel11 = new javax.swing.JPanel();
        jTextField11111 = new javax.swing.JTextField();
        jSearchScrollPane11 = new javax.swing.JScrollPane();
        jSearchTable11 = new dbadmin.JTable();
        jButton511 = new javax.swing.JButton();
        buttonGroup1 = new javax.swing.ButtonGroup();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel4 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        postbtn = new javax.swing.JButton();
        cancelbtn = new javax.swing.JButton();
        exitbtn = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        externalprtbl = new dbadmin.JTable();
        jPanel41 = new javax.swing.JPanel();
        jScrollPane21 = new javax.swing.JScrollPane();
        jTextPane4 = new javax.swing.JTextPane();
        jPanel6 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        deptRaising = new javax.swing.JComboBox();
        issuingCmbx = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel111 = new javax.swing.JLabel();
        userTxt = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jPanel61 = new javax.swing.JPanel();
        oldReqNotxt = new javax.swing.JTextField();
        searchButton1 = new javax.swing.JButton();
        dueDpckr = new dbadmin.DatePicker();
        jPanel12 = new javax.swing.JPanel();
        reqNotxt = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        reqdatepicer = new dbadmin.DatePicker();

        itemsReqDialog.setModal(true);
        itemsReqDialog.setUndecorated(true);
        itemsReqDialog.getContentPane().setLayout(new java.awt.GridBagLayout());

        jSearchPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jSearchPanel1.setLayout(new java.awt.GridBagLayout());

        jTextField1111.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                jTextField1111CaretUpdate(evt);
            }
        });
        jTextField1111.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1111ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 10.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 100);
        jSearchPanel1.add(jTextField1111, gridBagConstraints);

        itemsReqtbl.setShowHorizontalLines(false);
        /*    try {
            searchRowSet.setCommand("select product,selling_price,gl_code FROM st_stock_prices WHERE department = 'Pharmacy' order by product");
            searchRowSet.setConnectionSource(pConnDB);

            searchRowSet.execute();

            // crset2.setExecuteOnLoad(true);
            jSearchTable.setModel(new org.netbeans.lib.sql.models.TableModel(searchRowSet, new org.netbeans.lib.sql.models.TableModel.Column[] {
                new org.netbeans.lib.sql.models.TableModel.Column("product", "Description", false),
                new org.netbeans.lib.sql.models.TableModel.Column("selling_price", "Amount", false),
                new org.netbeans.lib.sql.models.TableModel.Column("gl_code", "Gl_code", false)

            }));
            // jSearchScrollPane.setViewportView(jSearchTable);

        } catch(java.sql.SQLException sqlex){
            javax.swing.JOptionPane.showMessageDialog(this,sqlex.getMessage(),"Error Message!",javax.swing.JOptionPane.ERROR_MESSAGE);

            System.out.println(sqlex.getMessage());
        }
        */
        itemsReqtbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                itemsReqtblMouseClicked(evt);
            }
        });
        jSearchScrollPane1.setViewportView(itemsReqtbl);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 20.0;
        jSearchPanel1.add(jSearchScrollPane1, gridBagConstraints);

        jButton91.setText("Dispose");
        jButton91.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton91ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        jSearchPanel1.add(jButton91, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        itemsReqDialog.getContentPane().add(jSearchPanel1, gridBagConstraints);

        jSearchDialog11.setModal(true);
        jSearchDialog11.setUndecorated(true);
        jSearchDialog11.getContentPane().setLayout(new java.awt.GridBagLayout());

        jSearchPanel11.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jSearchPanel11.setLayout(new java.awt.GridBagLayout());

        jTextField11111.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                jTextField11111CaretUpdate(evt);
            }
        });
        jTextField11111.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField11111ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 300.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 5);
        jSearchPanel11.add(jTextField11111, gridBagConstraints);

        jSearchTable11.setToolTipText("Click on the target row to select the patient from the search.");
        jSearchTable11.setShowHorizontalLines(false);
        /*javax.swing.table.TableColumn column = null;

        for (int i = 0; i < 4; i++) {

            column = jSearchTable.getColumnModel().getColumn(i);

            if (i == 1) {

                column.setPreferredWidth(400);
                //sport column is bigger
            } else {

                column.setPreferredWidth(200);

            }
        }
        */
        jSearchTable11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jSearchTable11MouseClicked(evt);
            }
        });
        jSearchScrollPane11.setViewportView(jSearchTable11);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 20.0;
        jSearchPanel11.add(jSearchScrollPane11, gridBagConstraints);

        jButton511.setText("Close");
        jButton511.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton511ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        jSearchPanel11.add(jButton511, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        jSearchDialog11.getContentPane().add(jSearchPanel11, gridBagConstraints);

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setPreferredSize(new java.awt.Dimension(1000, 500));
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameOpened(evt);
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
        });
        getContentPane().setLayout(new java.awt.GridBagLayout());

        jTabbedPane1.setTabLayoutPolicy(javax.swing.JTabbedPane.SCROLL_TAB_LAYOUT);
        jTabbedPane1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTabbedPane1MouseClicked(evt);
            }
        });

        jPanel4.setLayout(new java.awt.GridBagLayout());

        jPanel1.setLayout(new java.awt.GridBagLayout());
        jPanel4.add(jPanel1, new java.awt.GridBagConstraints());

        jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel3.setLayout(new java.awt.GridBagLayout());

        postbtn.setBackground(new java.awt.Color(0, 204, 204));
        postbtn.setMnemonic('s');
        postbtn.setText("             Save           ");
        postbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                postbtnActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        jPanel3.add(postbtn, gridBagConstraints);

        cancelbtn.setBackground(new java.awt.Color(0, 204, 204));
        cancelbtn.setMnemonic('l');
        cancelbtn.setText("     Clear Form    ");
        cancelbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelbtnActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        jPanel3.add(cancelbtn, gridBagConstraints);

        exitbtn.setBackground(new java.awt.Color(0, 204, 204));
        exitbtn.setMnemonic('c');
        exitbtn.setText("Close Form");
        exitbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitbtnActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        jPanel3.add(exitbtn, gridBagConstraints);

        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridwidth = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        jPanel3.add(jLabel5, gridBagConstraints);

        jButton1.setBackground(new java.awt.Color(0, 204, 204));
        jButton1.setMnemonic('r');
        jButton1.setText("    Remove Row    ");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        jPanel3.add(jButton1, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 0.1;
        jPanel4.add(jPanel3, gridBagConstraints);

        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel2.setLayout(new java.awt.GridBagLayout());

        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_ALWAYS);
        jScrollPane1.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);
        jScrollPane1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jScrollPane1MouseClicked(evt);
            }
        });

        externalprtbl.setBackground(new java.awt.Color(204, 204, 204));
        externalprtbl.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        externalprtbl.setForeground(new java.awt.Color(0, 0, 204));
        externalprtbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Item Code", "Item Description", "Units", "Strength", "Quantity", "Stock Balance"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Double.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                true, true, false, false, true, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        externalprtbl.setRowHeight(20);
        externalprtbl.getTableHeader().setReorderingAllowed(false);
        /*java.lang.Object[] strCmb = {"Normal","Urgent",""};

        javax.swing.JComboBox cmBox = new javax.swing.JComboBox(strCmb);

        javax.swing.table.TableColumn teditor = this.jTable1.getColumn("Status");

        teditor.setCellEditor(new javax.swing.DefaultCellEditor(cmBox));
        */

        javax.swing.table.TableColumn column = null;
        for (int i = 0; i < 4; i++) {
            column = externalprtbl.getColumnModel().getColumn(i);
            if (i == 0) {

                column.setPreferredWidth(300); //sport column is bigger
            } else {
                if (i == 1) {
                    column.setPreferredWidth(200);
                } else {
                    //if (i == 2) {
                        column.setPreferredWidth(200);
                        // }  else
                    //column.setPreferredWidth(50);

                }
            }
        }
        externalprtbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                externalprtblMouseReleased(evt);
            }
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                externalprtblMouseClicked(evt);
            }
        });
        externalprtbl.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                externalprtblKeyReleased(evt);
            }
        });
        jScrollPane1.setViewportView(externalprtbl);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 500.0;
        jPanel2.add(jScrollPane1, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 10.0;
        jPanel4.add(jPanel2, gridBagConstraints);

        jPanel41.setBorder(javax.swing.BorderFactory.createTitledBorder("Brief Summary"));
        jPanel41.setLayout(new java.awt.GridBagLayout());

        jScrollPane21.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jTextPane4.setText("ok");
        jScrollPane21.setViewportView(jTextPane4);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 2.0;
        gridBagConstraints.weighty = 1.0;
        jPanel41.add(jScrollPane21, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 0.3;
        jPanel4.add(jPanel41, gridBagConstraints);

        jPanel6.setLayout(new java.awt.GridBagLayout());

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder("Requisition Details"));
        jPanel5.setLayout(new java.awt.GridBagLayout());

        jLabel3.setText("Requisitioning Store");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 20);
        jPanel5.add(jLabel3, gridBagConstraints);

        deptRaising.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        deptRaising.setModel(dbadmin.ComboBoxModel.ComboBoxModel(connectDB, "SELECT '-' UNION SELECT DISTINCT store_name FROM public.inventory_stores ORDER BY 1;"));
        deptRaising.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deptRaisingActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 20, 0, 100);
        jPanel5.add(deptRaising, gridBagConstraints);

        issuingCmbx.setModel(dbadmin.ComboBoxModel.ComboBoxModel(connectDB, "SELECT '-' UNION SELECT DISTINCT store_name FROM public.inventory_stores ORDER BY 1"));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(0, 20, 0, 100);
        jPanel5.add(issuingCmbx, gridBagConstraints);

        jLabel2.setForeground(new java.awt.Color(255, 0, 0));
        jLabel2.setText("Issuing Store");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        jPanel5.add(jLabel2, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        jPanel6.add(jPanel5, gridBagConstraints);

        jPanel7.setLayout(new java.awt.GridBagLayout());

        jLabel4.setText("Due Date");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 20);
        jPanel7.add(jLabel4, gridBagConstraints);

        jLabel8.setText("Entered By");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 20);
        jPanel7.add(jLabel8, gridBagConstraints);

        jLabel111.setText("Requisition Date");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 20);
        jPanel7.add(jLabel111, gridBagConstraints);

        userTxt.setEditable(false);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        jPanel7.add(userTxt, gridBagConstraints);

        jLabel1.setForeground(new java.awt.Color(0, 0, 255));
        jLabel1.setText("**Use Existing Req no");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 20);
        jPanel7.add(jLabel1, gridBagConstraints);

        jPanel61.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel61.setMinimumSize(new java.awt.Dimension(82, 37));
        jPanel61.setLayout(new java.awt.GridBagLayout());

        oldReqNotxt.setEditable(false);
        oldReqNotxt.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                oldReqNotxtCaretUpdate(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        jPanel61.add(oldReqNotxt, gridBagConstraints);

        searchButton1.setToolTipText("Search");
        searchButton1.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        searchButton1.setMaximumSize(new java.awt.Dimension(74, 53));
        searchButton1.setMinimumSize(new java.awt.Dimension(74, 53));
        searchButton1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        searchButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchButton1ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        jPanel61.add(searchButton1, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        jPanel7.add(jPanel61, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        jPanel7.add(dueDpckr, gridBagConstraints);

        jPanel12.setLayout(new java.awt.GridBagLayout());

        reqNotxt.setEditable(false);
        reqNotxt.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        jPanel12.add(reqNotxt, gridBagConstraints);

        jLabel6.setText("Req No");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.weightx = 1.0;
        jPanel12.add(jLabel6, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.gridheight = 5;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        jPanel7.add(jPanel12, gridBagConstraints);

        reqdatepicer.setEnabled(false);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        jPanel7.add(reqdatepicer, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        jPanel6.add(jPanel7, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        jPanel4.add(jPanel6, gridBagConstraints);

        jTabbedPane1.addTab("Products In The Catalog", jPanel4);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        getContentPane().add(jTabbedPane1, gridBagConstraints);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void postbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_postbtnActionPerformed

        String transNo = null;
        Boolean status = false;

        try {

            connectDB.setAutoCommit(false);

            if (oldReqNotxt.getText().length() < 1) {

                java.sql.Statement ps = connectDB.createStatement();

                java.sql.ResultSet rs2 = ps.executeQuery("select 'RQ'||lpad(nextval('proc_req_no_seq')::text,6,0::TEXT)");
                while (rs2.next()) {
                    transNo = rs2.getObject(1).toString();
                    reqNotxt.setText(transNo);
                }
            } else {
                transNo = oldReqNotxt.getText();
            }
            int j = 0;
            if (externalprtbl.getModel().getValueAt(j, 0) != null) {

                java.sql.PreparedStatement pstmt = connectDB.prepareStatement("INSERT INTO public.inventory_requisitions(\n"
                        + "            item_code, unit, strength, quantity_required, quantity_issued, \n"
                        + "            requisitioning_store, issuing_store, requisition_no, date_requested,due_date, \n"
                        + "            comments, requisition_type)\n"
                        + "    VALUES (?, ?, ?, ?, ?, \n"
                        + "            ?, ?, ?, ?, \n"
                        + "            ?, ?, ?);");

                for (int i = 0; i < externalprtbl.getRowCount(); i++) {

                    if (externalprtbl.getModel().getValueAt(i, 0) != null && externalprtbl.getModel().getValueAt(i, 3) != null) {
                        //usage

                        JOptionCheck = true;
                        pstmt.setObject(1, externalprtbl.getValueAt(i, 0).toString());
                        pstmt.setObject(2, externalprtbl.getValueAt(i, 2).toString());
                        pstmt.setString(3, externalprtbl.getValueAt(i, 3).toString());
                        pstmt.setDouble(4, Double.valueOf(externalprtbl.getValueAt(i, 4).toString()));
                        pstmt.setDouble(5, 0.00);
                        pstmt.setObject(6, deptRaising.getSelectedItem().toString());
                        pstmt.setObject(7, issuingCmbx.getSelectedItem().toString());
                        pstmt.setString(8, transNo);
                        pstmt.setDate(9, dbadmin.SQLDateFormat.getSQLDate(reqdatepicer.getDate()));
                        pstmt.setDate(10, dbadmin.SQLDateFormat.getSQLDate(dueDpckr.getDate()));
                        pstmt.setObject(11, jTextPane4.getText());
                        pstmt.setObject(12, "RQ");

                        pstmt.executeUpdate();

                    } else {
                        if (i == 0) {
                            JOptionPane.showMessageDialog(null, "Enter all the Highlighted values in the Table");
                        }

                    }

                }

                connectDB.commit();
                connectDB.setAutoCommit(true);

                javax.swing.JOptionPane.showMessageDialog(this, "Insert Done Successfully Requisition No. is '" + transNo + "'", "Comfirmation", javax.swing.JOptionPane.INFORMATION_MESSAGE);

                j++;
            } else {
                status = false;
                javax.swing.JOptionPane.showMessageDialog(this, "Please add item(s)", "Error Message!", javax.swing.JOptionPane.ERROR_MESSAGE);
            }

            if (status = true) {
                jTextPane4.setText(null);
                for (int k = 0; k < externalprtbl.getRowCount(); k++) {
                    for (int r = 0; r < externalprtbl.getColumnCount(); r++) {
                        externalprtbl.getModel().setValueAt(null, k, r);
                    }
                }

            } else {

            }

        } catch (java.sql.SQLException sq) {
            javax.swing.JOptionPane.showMessageDialog(this, sq.getMessage(), "Error Message!", javax.swing.JOptionPane.ERROR_MESSAGE);
            sq.printStackTrace();
            try {
                connectDB.rollback();
            } catch (java.sql.SQLException sql) {
                javax.swing.JOptionPane.showMessageDialog(this, sql.getMessage(), "Error Message!", javax.swing.JOptionPane.ERROR_MESSAGE);
            }
        }

        // Add your handling code here:
    }//GEN-LAST:event_postbtnActionPerformed

    private void cancelbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelbtnActionPerformed
        for (int k = 0; k < externalprtbl.getRowCount(); k++) {
            for (int r = 0; r < externalprtbl.getColumnCount(); r++) {
                externalprtbl.getModel().setValueAt(null, k, r);
            }
        }
        jTextPane4.setText("");

        reqNotxt.setText("");
        oldReqNotxt.setText("");
        // Add your handling code here:
    }//GEN-LAST:event_cancelbtnActionPerformed

    private void exitbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitbtnActionPerformed
        this.setVisible(false);   // Add your handling code here:
    }//GEN-LAST:event_exitbtnActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        int rows2Delete = externalprtbl.getSelectedRowCount();

        int[] selectedRows = externalprtbl.getSelectedRows();

        if (rows2Delete < 1) {

            java.awt.Toolkit.getDefaultToolkit().beep();

            javax.swing.JOptionPane.showMessageDialog(this, "There are no selected rows to delete!");

        } else {

            if (rows2Delete > 1) {

                for (int i = 0; i < selectedRows.length; i++) {

                    javax.swing.table.DefaultTableModel defTableModel = (javax.swing.table.DefaultTableModel) externalprtbl.getModel();

                    defTableModel.removeRow(selectedRows[i]);

                }

            } else {

                javax.swing.table.DefaultTableModel defTableModel = (javax.swing.table.DefaultTableModel) externalprtbl.getModel();

                defTableModel.removeRow(externalprtbl.getSelectedRow());
            }
        }        // Add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void externalprtblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_externalprtblMouseClicked
        if (externalprtbl.getSelectedColumn() == 0) {

            this.cmbox11MouseClicked();
        }

        // Add your handling code here:
    }//GEN-LAST:event_externalprtblMouseClicked

    private void externalprtblKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_externalprtblKeyReleased

        double bal = 0.00;
        try {
            java.sql.Statement pstmt = connectDB.createStatement();
            java.sql.ResultSet rs = pstmt.executeQuery("select sum(QTY) from stock_balance_qty  WHERE item_code = '" + externalprtbl.getValueAt(externalprtbl.getSelectedRow(), 0) + "' AND department ILIKE '" + deptRaising.getSelectedItem().toString().toUpperCase() + "'");
            while (rs.next()) {

                bal = rs.getDouble(1);
                externalprtbl.setValueAt(java.lang.String.valueOf(bal), externalprtbl.getSelectedRow(), 4);
                //jComboBox1.setSelectedItem(rs.getString(1));
            }
        } catch (java.sql.SQLException sqlex) {
            System.out.println(sqlex.getMessage());

        }
    }//GEN-LAST:event_externalprtblKeyReleased

    private void deptRaisingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deptRaisingActionPerformed

        // Add your handling code here:
    }//GEN-LAST:event_deptRaisingActionPerformed

    private void oldReqNotxtCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_oldReqNotxtCaretUpdate
        // TODO add your handling code here:
        jSearchTable11.setModel(dbadmin.TableModel.createTableVectors(connectDB, "SELECT requisition_no FROM st_receive_requisation WHERE (requisition_no ilike 'PRQ%' or requisition_no ilike '%" + oldReqNotxt.getText().toString() + "%'  ) and processed = false"));
//        }
        jSearchScrollPane11.setViewportView(jSearchTable11);
    }//GEN-LAST:event_oldReqNotxtCaretUpdate

    private void searchButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchButton1ActionPerformed
        this.cmboxMouseClicked();
    }//GEN-LAST:event_searchButton1ActionPerformed
    private void cmboxMouseClicked() {
        System.out.println("Showing dialog");
        java.awt.Point point = oldReqNotxt.getLocationOnScreen();
        jSearchDialog11.setSize(350, 200);
        jSearchDialog11.setLocation(point);
        jSearchDialog11.setVisible(true);
    }
    private void jScrollPane1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jScrollPane1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jScrollPane1MouseClicked

    private void jTextField1111CaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_jTextField1111CaretUpdate

        if (jTextField1111.getCaretPosition() > 2) {
            itemsReqtbl.setModel(dbadmin.TableModel.createTableVectorsCaret(connectDB, "SELECT item_code, item_name, smallest_unit,strength \n"
                    + "  FROM public.inventory_items WHERE item_code ILIKE '%" + jTextField1111.getText() + "%' OR item_name ILIKE '%" + jTextField1111.getText() + "%';"));

            jSearchScrollPane1.setViewportView(itemsReqtbl);
        }

        // Add your handling code here:
    }//GEN-LAST:event_jTextField1111CaretUpdate

    private void itemsReqtblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_itemsReqtblMouseClicked
        double bal = 0.00;

        externalprtbl.setValueAt(itemsReqtbl.getValueAt(itemsReqtbl.getSelectedRow(), 0), externalprtbl.getSelectedRow(), 0);
        externalprtbl.setValueAt(itemsReqtbl.getValueAt(itemsReqtbl.getSelectedRow(), 1), externalprtbl.getSelectedRow(), 1);
        externalprtbl.setValueAt(itemsReqtbl.getValueAt(itemsReqtbl.getSelectedRow(), 2), externalprtbl.getSelectedRow(), 2);
        externalprtbl.setValueAt(itemsReqtbl.getValueAt(itemsReqtbl.getSelectedRow(), 3), externalprtbl.getSelectedRow(), 3);

        itemsReqDialog.dispose();
        // Add your handling code here:
    }//GEN-LAST:event_itemsReqtblMouseClicked

    private void jButton91ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton91ActionPerformed
        this.itemsReqDialog.dispose();        // Add your handling code here:
    }//GEN-LAST:event_jButton91ActionPerformed

    private void jTextField1111ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1111ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1111ActionPerformed

    private void jTextField11111CaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_jTextField11111CaretUpdate
        // int j = 0;
        // try {
        //  java.sql.Statement stmt = connectDB.createStatement();
        // java.sql.ResultSet rset = stmt.executeQuery("SELECT count(requisition_no) FROM st_receive_requisation WHERE requisition_no ilike 'PRQ%' and processed = false");

        //   while (rset.next()) {
        //      j = rset.getInt(1);
        //  }
        //  if (j > 0){
        jSearchTable11.setModel(dbadmin.TableModel.createTableVectorsCaret(connectDB, "select distinct requisition_no as Req_No from st_receive_requisation where requisition_no ILIKE '" + jTextField11111.getText().toString() + "%' and (requisition_no ilike 'PRQ%' OR requisition_no ilike 'SRQ%') AND analysed=FALSE ORDER BY requisition_no"));
                //   }
            /*   try {
         searchRowSet1.execute("select distinct order_no as scheme,(supplier) as name from st_orders where order_no ILIKE '"+jTextField1111.getText().toString()+"%' ORDER BY order_no");

         jSearchTable1.setModel(new org.netbeans.lib.sql.models.TableModel(searchRowSet1, new org.netbeans.lib.sql.models.TableModel.Column[] {
         new org.netbeans.lib.sql.models.TableModel.Column("scheme", "Order No.", false),
         new org.netbeans.lib.sql.models.TableModel.Column("name", "Supplier", false),
         // new org.netbeans.lib.sql.models.TableModel.Column("account_no", "Acc No.", false)
         }));
         */

        //   } catch(java.sql.SQLException sqlExec) {
        //      javax.swing.JOptionPane.showMessageDialog(this, sqlExec.getMessage());
        //   }
        jSearchTable11.setShowHorizontalLines(false);
        jSearchScrollPane11.setViewportView(jSearchTable11);

        // Add your handling code here:
    }//GEN-LAST:event_jTextField11111CaretUpdate

    private void jTextField11111ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField11111ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField11111ActionPerformed

    private void jSearchTable11MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jSearchTable11MouseClicked
        if (jTabbedPane1.getSelectedIndex() == 0) {
            oldReqNotxt.setText(jSearchTable11.getValueAt(jSearchTable11.getSelectedRow(), 0).toString());
            //    jTextField361.setText(jSearchTable1.getValueAt(jSearchTable1.getSelectedRow(), 1).toString());
            jSearchDialog11.dispose();
            for (int k = 0; k < externalprtbl.getRowCount(); k++) {
                for (int r = 0; r < externalprtbl.getColumnCount(); r++) {
                    externalprtbl.getModel().setValueAt(null, k, r);
                }
            }

            int k = 0;

            this.postbtn.setEnabled(true);
            this.populateTable11(this.oldReqNotxt.getText());
        }// Add your handling code here:
        else if (jTabbedPane1.getSelectedIndex() == 1) {

            reqNotxt.setText(jSearchTable11.getValueAt(jSearchTable11.getSelectedRow(), 0).toString());
//            jComboBox1.setModel(lib.ComboBoxModel.ComboBoxModel(connectDB, " select distinct item_description from st_receive_requisation where  requisition_no='" + reqNotxt.getText() + "' order by 1 "));
            this.jSearchDialog11.dispose();

        }
    }//GEN-LAST:event_jSearchTable11MouseClicked
    private void populateTable11(java.lang.String patient_no) {
        int i = 0;
        try {

            //   for (int i = 0; i < jTable1.getRowCount(); i++ ) {
            //       if (jTable1.getModel().getValueAt(i,0) != null){
            java.sql.Statement stmtTable = connectDB.createStatement();

            java.sql.ResultSet rsetTable = stmtTable.executeQuery("SELECT item_description,units,quantity::numeric,price,(quantity*price::numeric)::numeric(15,2),balance,reason FROM st_receive_requisation WHERE requisition_no ilike '" + oldReqNotxt.getText() + "' order by item_description");
            //  java.sql.ResultSet rsetTable111 = stmtTable111.executeQuery("SELECT sum(receiving-issuing) FROM st_sub_stores WHERE store_name = '"+jTextField1.getText().equalsIgnoreCase(jTextField1.getText())+"' and item = '"+jTable1.getValueAt(k,0).toString()+"'");

            while (rsetTable.next()) {
                java.sql.Statement stmtTable1 = connectDB.createStatement();
                java.sql.ResultSet rsetTablex = stmtTable1.executeQuery("SELECT item_code FROM st_stock_item where description='" + rsetTable.getObject(1).toString() + "' ");

                externalprtbl.setValueAt(rsetTable.getObject(1), i, 1);
                externalprtbl.setValueAt(rsetTable.getObject(2), i, 2);
                externalprtbl.setValueAt(rsetTable.getObject(3), i, 3);
                externalprtbl.setValueAt(rsetTable.getObject(7), i, 5);
                externalprtbl.setValueAt(rsetTable.getObject(6), i, 4);
                while (rsetTablex.next()) {
                    externalprtbl.setValueAt(rsetTablex.getObject(1), i, 0);
                }
                jTextPane4.setText(rsetTable.getString(7));
                //  jTable1.setValueAt("0.00", i, 5);
                // jTable1.setValueAt(rsetTable.getObject(5), i, 6);
                //   jTable1.setValueAt(rsetTable1.getObject(6), i, 6);

                i++;

            }

            /*
             java.sql.Statement stmtTablez = connectDB.createStatement();
            
             java.sql.ResultSet rsetTablez = stmtTablez.executeQuery("SELECT DISTINCT cost_center FROM st_receive_requisation WHERE requisition_no ilike '"+jTextField361.getText()+"'");
             while (rsetTablez.next()) {
             jTextField10.setText(rsetTablez.getObject(1).toString());
             }
             */
        } catch (java.sql.SQLException sqlExec) {

            javax.swing.JOptionPane.showMessageDialog(this, sqlExec.getMessage());

        }
    }

    private void jButton511ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton511ActionPerformed
        jSearchDialog11.dispose();    // Add your handling code here:
    }//GEN-LAST:event_jButton511ActionPerformed

    private void formInternalFrameOpened(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameOpened
        // TODO add your handling code here:
        //     goodsPrqChbx.setSelected(true);
        // requistnCmbx.setModel(lib.ComboBoxModel.ComboBoxModel(connectDB, "(select store_name from st_main_stores where code ilike '%M%'  union select '-') order by 1"));
    }//GEN-LAST:event_formInternalFrameOpened

    private void jTabbedPane1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTabbedPane1MouseClicked
        // TODO add your handling code here:
//        if (jTabbedPane1.getSelectedIndex() == 1) {
//            try {
//                if (reqNotxt.getText().isEmpty()) {
//                    jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[]{"-"}));
//                } else {
//                    jComboBox1.setModel(lib.ComboBoxModel.ComboBoxModel(connectDB, " select distinct item_description from st_receive_requisation where  requisition_no='" + reqNotxt.getText() + "' order by 1 "));
//
//                }
//
//            } catch (Exception ex) {
//                ex.printStackTrace();
//            }

        // }
    }//GEN-LAST:event_jTabbedPane1MouseClicked
    private void cleartbl() {
//        for (int k = 0; k < specsTbl.getRowCount(); k++) {
//            for (int r = 0; r < specsTbl.getColumnCount(); r++) {
//                specsTbl.getModel().setValueAt(null, k, r);
//            }
//        }

    }
    private void externalprtblMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_externalprtblMouseReleased
        // TODO add your handling code here:

    }//GEN-LAST:event_externalprtblMouseReleased
    private void cmbox11MouseClicked() {
        System.out.println("Showing dialog");
        java.awt.Point point = jScrollPane1.getLocationOnScreen();
        itemsReqDialog.setSize(600, 200);
        itemsReqDialog.setLocation(point);
        itemsReqDialog.setVisible(true);
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton cancelbtn;
    private javax.swing.JComboBox deptRaising;
    private dbadmin.DatePicker dueDpckr;
    public static javax.swing.JButton exitbtn;
    private javax.swing.JTable externalprtbl;
    private javax.swing.JComboBox issuingCmbx;
    private javax.swing.JDialog itemsReqDialog;
    private javax.swing.JTable itemsReqtbl;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton511;
    private javax.swing.JButton jButton91;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel111;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel41;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel61;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane21;
    private javax.swing.JDialog jSearchDialog11;
    private javax.swing.JPanel jSearchPanel1;
    private javax.swing.JPanel jSearchPanel11;
    private javax.swing.JScrollPane jSearchScrollPane1;
    private javax.swing.JScrollPane jSearchScrollPane11;
    private javax.swing.JTable jSearchTable11;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextField jTextField1111;
    private javax.swing.JTextField jTextField11111;
    private javax.swing.JTextPane jTextPane4;
    private javax.swing.JTextField oldReqNotxt;
    private javax.swing.JButton postbtn;
    private javax.swing.JTextField reqNotxt;
    private dbadmin.DatePicker reqdatepicer;
    private javax.swing.JButton searchButton1;
    private javax.swing.JTextField userTxt;
    // End of variables declaration//GEN-END:variables
}
